# Generated by Django 3.1.12 on 2024-06-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
    ]
